### ISSUE TITLE
Support Android via Jetpack Compose

### ISSUE THREAD

**Issue by liambutler-lawrence** [andrew-levy/swiftui-react-native#44]
Are there any plans to add support for Android? Our RN app is already live on both platforms so as amazing as this library looks, we couldn't switch until it has Android support.

Fortunately, Jetpack Compose is not 1:1 but extremely close to SwiftUI in terms of API, so shouldn't require many compromises.

**Comment by andrew-levy** [comment]
@liambutler-lawrence I've thought about this, but decided against it for a few reasons. 

1. I think that might be out of scope for this project, especially since I'm the only one working on it and it's already a lot to maintain. Though any help would be appreciated if you want to see this happen :)

2. This library isn't meant to be a component library, per se, but more like a toolkit to reach for when you need specific swiftui features. 

3. Even though they have similar apis, it sometimes feels like trying to fit a square peg into a round hole to make the apis match up. 

I'd be open to trying to make this work if we can do it right.
