### ISSUE TITLE
List not working...

### ISSUE THREAD

**Issue by rit3zh** [andrew-levy/swiftui-react-native#60]
What's this new bug?

The list is not working the way it should work…

<img width="1710" alt="Screenshot 2024-12-22 at 10 27 04 PM" src="https://github.com/user-attachments/assets/650ee496-0eb9-4e32-acef-f8582e45c467" />

**Comment by andrew-levy** [comment]
I'm not using nativewind, but I'm replicating your setup and not able to reproduce. Maybe Nativewind is causing issues? Are you using the most recent version? Let me know @rit3zh 

<img width="1059" alt="Screenshot 2024-12-23 at 5 34 35 AM" src="https://github.com/user-attachments/assets/5c340d05-461b-477f-88c8-b8c6443a9438" />

**Comment by rit3zh** [comment]
Yeah, i'm using the most recent version. I don't think so Nativwind is causing triggering this issue, I've used Nativewind with the library before and it worked absolutely fine. I am using expo 52.

Here's a screenshot of my package.json for your reference.

<img width="1352" alt="Screenshot 2024-12-23 at 12 18 18 PM" src="https://github.com/user-attachments/assets/ea8c34cb-9723-46aa-b908-ea769b3c3c94" />

**Comment by andrew-levy** [comment]
Do you have the new architecture enabled? This library currently doesn't support new arch yet. @rit3zh

**Comment by andrew-levy** [comment]
if not, can you try doing what I did in my example to see if that works?

**Comment by rit3zh** [comment]
Alright, you're correct the problem is with the new architecture. I've made the same app downgrading my expo version to "~51.0.28" and it works fine.

<img width="1710" alt="Screenshot 2024-12-23 at 1 20 24 PM" src="https://github.com/user-attachments/assets/d6508674-8711-4e26-8ffe-08adeaf5d2fa" />

**Comment by andrew-levy** [comment]
Okay makes sense. Thanks for checking. I tried to make it new arch compatible last month, but ran into issues. Going to try again soon tho

**Comment by mgcrea** [comment]
Just stumbled on this, all the examples were blank since the <List /> native elements do not seem to be rendering properly with `expo@52`.

Maybe we could add some warning in the README/docs to specify the last compatible expo version? Hopefully the project can migrate to the new arch pretty soon.

Anyway thank you for the great lib, it has great potential! Looking forward to new releases.

**Comment by mgcrea** [comment]
Just stumbled on this, all the examples were blank since the <List /> native elements do not seem to be rendering properly.

Maybe we could add some warning in the README/docs to specify the last compatible expo version? Hopefully the project can migrate to the new arch pretty soon.

Anyway thank you for the great lib, it has great potential! Looking forward to new releases.

**Comment by andrew-levy** [comment]
Yes I will add a note to the docs. This library doesn't support the new architecture. It looks like expo is building a new arch supported version of this library internally, so eventually I will just suggest people to use theirs over this, no need to have two libraries that do the same thing.
