### ISSUE TITLE
Compatible with Expo?

### ISSUE THREAD

**Issue by cloudorbush** [andrew-levy/swiftui-react-native#7]
Is your libary compatible with expo?

Thank you

**Comment by andrew-levy** [comment]
@10000multiplier Hey. I haven't tried using this with Expo yet, so I'm not entirely sure. This project was more of an "experiment" rather than a production ready library, but I am working on cleaning things up for v2.0.0 coming in the near future. The plan is to be compatible with expo, remove a bunch of unnecessary and out of date components (like all the navigation components - they made the lib heavy and hard to work with), and clean up a lot of the code.

**Comment by zpg6** [comment]
@andrew-levy I see you've since released v2.0.0, did you have a chance to test that with Expo? 

Flexbox layout makes no sense to me and having dabbled in most of the app frameworks, I'm the biggest fan of SwiftUI's way of doing things (`HStack`, `VStack`, `ZStack`, and `Spacer`). How stable would you say those are in v2.0.0 with/without Expo? 

Thanks in advance

**Comment by andrew-levy** [comment]
Hey @zpg6. If you're just interested in using the stack and spacer views, check out this library https://github.com/andrew-levy/react-native-stacks. Its much smaller and doesn't have any native code. I wrote this library as just an experiment to build out swiftui-like views so it's not well maintained, unfortunately. It would require some extra steps to work with expo but I haven't gone through the steps yet. Hope this helps!

**Comment by zpg6** [comment]
Awesome, thanks for the quick reply!

**Comment by andrew-levy** [comment]
@zpg6 these are the dependencies needed for the project:

- react-native-reanimated
- react-native-gesture-handler 
- react-native-sfsymbols

Expo has documentation on how to install the first two, but I'm not sure about sfsymbols. I believe you can configure expo to import native modules like this one. I think the only concession would be you can't use the expo go app. you can find more about that here https://docs.expo.dev/workflow/customizing/
